apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaoskube
  namespace: default
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - list
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: chaoskube
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaoskube
subjects:
- kind: ServiceAccount
  name: chaoskube
  namespace: chaoskube

